services:
  gcp_service:
    container_name: gcp_service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/apps/gcp_service
    stdin_open: true
    tty: true
